# Example IJulia Notebook

Check your installation

In [1]:
f(x, y) = x + y

f (generic function with 1 method)

In [2]:
f(2, 3)

5

# Variables and Printing

In [1]:
println("Hi there")

Hi there


In [5]:
123
456; # Supressed

In [10]:
power = 10 ^ 2

100

# Strings

In [11]:
s1 = "hi, I'm a string"

"hi, I'm a string"

In [12]:
s2 = """Just like Python
we can do this"""

"Just like Python\nwe can do this"

In [13]:
typeof('a')

Char

In [19]:
'this is not allowed like in c'

LoadError: syntax: character literal contains multiple characters

In [24]:
name = "Adam"
heightIn = 71
println("Hi, my name is $(name) and I'm $(heightIn*2.4)cm tall.")

Hi, my name is Adam and I'm 170.4cm tall.


In [26]:
string("We live in", " a society")

"We live in a society"

In [28]:
string(3, " times ", 3, " is ", 4)

"3 times 3 is 4"

In [31]:
s3 = "we all live";
s4 = "in a yellow submarine";

In [32]:
s3*s4

"we all livein a yellow submarine"

In [33]:
"$s3$s4"

"we all livein a yellow submarine"

# Data Structures

In [49]:
a = ["a"]

1-element Array{String,1}:
 "a"

In [ ]:
a.append

## Dictionaries

In [44]:
prices = Dict("mango" => "10p", "pineapple" => "15p")
# Type is any if multiple values are used in constructor
# - Otherwise, the types are enforced

Dict{String,String} with 2 entries:
  "mango"     => "10p"
  "pineapple" => "15p"

In [45]:
# prices["bananaaa"] = 10 # Invalid
prices["bananaaa"] = "10p"

"10p"

In [46]:
prices

Dict{String,String} with 3 entries:
  "mango"     => "10p"
  "bananaaa"  => "10p"
  "pineapple" => "15p"

In [47]:
prices["mango"]

"10p"

In [48]:
a = pop!(prices, "pineapple")

"15p"

## Tuples

In [50]:
bestAnimals = ("cats", "doggos", "zebras")

("cats", "doggos", "zebras")

In [53]:
bestAnimals[1] # Julia is 1-indexed!!

"cats"

In [62]:
# bestAnimals[1] = "bunnies" # Error: Tuples are immutable

## Arrays

In [63]:
fibonacci = [1, 1, 2, 3, 5, 8, 13] # Creates Array{Int64, 1}

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [65]:
mixed = [1, 2, "3"] # Creates Array{Any, 1}

3-element Array{Any,1}:
 1
 2
  "3"

In [70]:
companies = ["apple", "google", "microsoft"]

3-element Array{String,1}:
 "apple"
 "google"
 "microsoft"

In [71]:
companies[1]

"apple"

In [72]:
companies[3] = "amazon";

In [73]:
companies

3-element Array{String,1}:
 "apple"
 "google"
 "amazon"

In [74]:
push!(companies, "netflix")

4-element Array{String,1}:
 "apple"
 "google"
 "amazon"
 "netflix"

In [75]:
lastCompany = pop!(companies)

"netflix"

Arrays therefore are like stacks (LIFO)

In [76]:
numbers = [[1, 2, 3], [4, 5], [6, 7, 8, 9]] # Can have different sized

3-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5]
 [6, 7, 8, 9]

In [82]:
rand(2, 5)

2×5 Array{Float64,2}:
 0.140022  0.282759  0.994019  0.507056  0.645241
 0.761187  0.200193  0.112678  0.910874  0.382978

In [83]:
rand()

0.94837633877236

In [86]:
zeros(5, 5)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

# Loops

## While Loops

In [89]:
a = 0
while a < 5
    a += 1
    println(a)
end

1
2
3
4
5


## For Loops

In [90]:
for n in 1:5
    println(n)
end

1
2
3
4
5


In [91]:
pets = ["cat", "dog", "panda"]

for pet in pets
    println("I have a $pet")
end

I have a cat
I have a dog
I have a panda


In [95]:
for pet = pets
    println("I can use this syntax to show my $pet")
end

for pet ∈ pets
    println("Or I can use ∈ to show my $pet")
end

I can use this syntax to show my cat
I can use this syntax to show my dog
I can use this syntax to show my panda
Or I can use ∈ to show my cat
Or I can use ∈ to show my dog
Or I can use ∈ to show my panda


### Example

Create an addition table

In [96]:
m, n = 5, 5
A = zeros(m, n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [98]:
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

Or we can condense this with some syntactic sugar

In [100]:
B = zeros(m, n)
for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

Or we can use array comprehension

In [101]:
C = [i + j for i in 1:m, j in 1:n] # Kind of like python but prettier

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

# Functions

## How to declare a function

In [106]:
function sayhi(name)
    println("Hi there $name")
end

sayhi (generic function with 1 method)

In [107]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [108]:
sayhi("Bob")

Hi there Bob


In [109]:
f(4)

16

### Single Line Functions

In [110]:
sayhi2(name) = println("Hi $name, this is cool")

sayhi2 (generic function with 1 method)

In [112]:
sayhi2("Waluigi")

Hi Waluigi, this is cool


### Anonymous (lambda) functions

In [113]:
sayhi3 = name -> println("Hi $name, what's up")

#3 (generic function with 1 method)

In [114]:
sayhi3("Adam")

Hi Adam, what's up


## Duck-typing in Julia

Functions will work on any input that makes sense

In [115]:
sayhi(55595472)

Hi there 55595472


In [116]:
A = rand(3, 3)

3×3 Array{Float64,2}:
 0.381147  0.974354  0.776939
 0.123093  0.379669  0.513829
 0.516271  0.956759  0.180523

In [118]:
f(A) # Square of a matrix is well defined

3×3 Array{Float64,2}:
 0.666321  1.48465   0.937035
 0.358927  0.755695  0.383479
 0.407745  1.039     0.92531

In [119]:
v = rand(3)

3-element Array{Float64,1}:
 0.3331748698991739
 0.23258953123412396
 0.49466893190351624

In [121]:
# f(v) # Error: Not well-defined

## Mutating vs non-mutating functions

By convention, functions followed by `!` alter their contents and functions lacking `!` do not.

For example, lets compare `sort` and `sort!`

In [122]:
v = [3, 5, 2]

3-element Array{Int64,1}:
 3
 5
 2

In [123]:
sort(v)

3-element Array{Int64,1}:
 2
 3
 5

In [124]:
v

3-element Array{Int64,1}:
 3
 5
 2

In [125]:
sort!(v)

3-element Array{Int64,1}:
 2
 3
 5

In [126]:
v

3-element Array{Int64,1}:
 2
 3
 5

## Broadcasting

By placing a `.` between any function name and its arguments, we tell that function to broadcast over the elements of the input objects.

Lets look at the difference between `f()` and `f.()`

In [128]:
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [129]:
f(A)

3×3 Array{Int64,2}:
  30   36   42
  66   81   96
 102  126  150

As we saw before, we have

```
f(A) = A^2 = A * A

```

In [130]:
f.(A)

3×3 Array{Int64,2}:
  1   4   9
 16  25  36
 49  64  81

Now, you can see that the function is passed to each individual element of `A`, rather than treating `A` as a whole.

So now we can use `f.()` on `v`

In [131]:
f.(v)

3-element Array{Int64,1}:
  4
  9
 25

In [134]:
A .+ 2 .* f.(A) ./ A # All are element-wise operations

3×3 Array{Float64,2}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

This is equivalent to `broadcast(x -> x + 2 * f(x) / x, A)`

# Packages

Load packages with:

```julia
using PkgName
```

This also adds all the member functions to the namespace, similar to `using namespace PkgName` or `import * from PkgName`

In [138]:
# using PkgName # Loads the package and adds them to the namespace

# Plotting

In [169]:
import Pkg; Pkg.add("PlotlyJS")

  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`


In [170]:
using PlotlyJS

In [150]:
x = -3:0.1:3 # Range from -3 to 3 with 0.1 increments
f(x) = x^2
y = f.(x)

61-element Array{Float64,1}:
 9.0
 8.41
 7.839999999999999
 7.290000000000001
 6.760000000000001
 6.25
 5.76
 5.289999999999999
 4.840000000000001
 4.41
 4.0
 3.61
 3.24
 ⋮
 3.61
 4.0
 4.41
 4.840000000000001
 5.289999999999999
 5.76
 6.25
 6.760000000000001
 7.290000000000001
 7.839999999999999
 8.41
 9.0

In [161]:
plotlyjs()

Plots.PlotlyJSBackend()

In [162]:
plot(x, y, label="line")
scatter!(x, y, label="points") # We use scatter! to mutate the existing plot

<!DOCTYPE html>
 
 
 Plots.jl

## Fancier Example

In [163]:
globaltemperatures = [14.4, 14.5, 14.8, 15.2, 15.5, 15.8]
numpirates = [45000, 20000, 15000, 5000, 400, 17]

6-element Array{Int64,1}:
 45000
 20000
 15000
  5000
   400
    17

In [168]:
plot(numpirates, globaltemperatures, legend=false)
scatter!(numpirates, globaltemperatures, legend=false)

# Reverse x axis to see how temperature changes with time
xflip!()

# Add titles and labels
xlabel!("Number of pirates [approximate]")
ylabel!("Global Temperature (*C)")
title!("Influence of pirate population on global temperature")

<!DOCTYPE html>
 
 
 Plots.jl

## Subplots

To create subplots, we just name each of the infividual subplots and then wrap those names, along with a layout specification, in another `plot` call

In [173]:
p1 = plot(x, x)
p2 = plot(x, x.^2)
p3 = plot(x, x.^3)
p4 = plot(x, x.^4)
plot(p1, p2, p3, p4, layout=(2,2), legend=false)

<!DOCTYPE html>
 
 
 Plots.jl

# Multiple Dispatch

Specifying different methods for different types

In [174]:
methods(+)

# 207 methods for generic function "+":
[1] +(dt::Dates.DateTime, z::Dates.Month) in Dates at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Dates/src/arithmetic.jl:47
[2] +(dt::Dates.DateTime, y::Dates.Year) in Dates at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Dates/src/arithmetic.jl:23
[3] +(x::Dates.DateTime, y::Dates.Period) in Dates at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Dates/src/arithmetic.jl:76
[4] +(z::Complex{Bool}, x::Bool) in Base at complex.jl:287
[5] +(z::Complex{Bool}, x::Real) in Base at complex.jl:301
[6] +(c::BigInt, x::BigFloat) in Base.MPFR at mpfr.jl:399
[7] +(a::BigInt, b::BigInt, c::BigInt, d::BigInt, e::BigInt) in Base.GMP at gmp.jl:518
[8] +(a::BigInt, b::BigInt, c::BigInt, d::BigInt) in Base.GMP at gmp.jl:517
[9] +(a::BigInt, b::BigInt, c::BigInt) in Base.GMP at gmp.jl:516
[10] +(x::BigInt, y::BigInt) in Base.GMP at gmp.jl:476
[11] +(x::BigInt, c::Union{UInt16, UInt32, UInt64, UInt8}) in Base.GMP at gmp.jl:524
[12] +(x::BigInt, c::Union{Int16, Int32, Int64, Int8}) in Base.GMP at gmp.jl:530
[13] +(level::Base.CoreLogging.LogLevel, inc::Integer) in Base.CoreLogging at logging.jl:116
[14] +(B::BitArray{2}, J::LinearAlgebra.UniformScaling) in LinearAlgebra at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/LinearAlgebra/src/uniformscaling.jl:117
[15] +(::Missing, ::Missing) in Base at missing.jl:114
[16] +(::Missing) in Base at missing.jl:100
[17] +(::Missing, ::Number) in Base at missing.jl:115
[18] +(x::Float64, y::Float64) in Base at float.jl:401
[19] +(x::Bool, z::Complex{Bool}) in Base at complex.jl:286
[20] +(x::Bool, y::Bool) in Base at bool.jl:96
[21] +(x::Bool) in Base at bool.jl:93
[22] +(x::Bool, y::T) where T<:AbstractFloat in Base at bool.jl:103
[23] +(x::Bool, z::Complex) in Base at complex.jl:293
[24] +(x::Dates.Date, y::Dates.Day) in Dates at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Dates/src/arithmetic.jl:74
[25] +(x::Dates.Date, y::Dates.Week) in Dates at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Dates/src/arithmetic.jl:72
[26] +(dt::Dates.Date, z::Dates.Month) in Dates at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Dates/src/arithmetic.jl:54
[27] +(dt::Dates.Date, y::Dates.Year) in Dates at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Dates/src/arithmetic.jl:27
[28] +(dt::Dates.Date, t::Dates.Time) in Dates at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Dates/src/arithmetic.jl:19
[29] +(a::Pkg.Resolve.VersionWeight, b::Pkg.Resolve.VersionWeight) in Pkg.Resolve at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Pkg/src/Resolve/versionweights.jl:22
[30] +(a::Pkg.Resolve.FieldValue, b::Pkg.Resolve.FieldValue) in Pkg.Resolve at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Pkg/src/Resolve/fieldvalues.jl:43
[31] +(t::Dates.Time, dt::Dates.Date) in Dates at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Dates/src/arithmetic.jl:20
[32] +(x::Dates.Time, y::Dates.TimePeriod) in Dates at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Dates/src/arithmetic.jl:78
[33] +(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat, e::BigFloat) in Base.MPFR at mpfr.jl:548
[34] +(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat) in Base.MPFR at mpfr.jl:541
[35] +(a::BigFloat, b::BigFloat, c::BigFloat) in Base.MPFR at mpfr.jl:535
[36] +(x::BigFloat, c::BigInt) in Base.MPFR at mpfr.jl:394
[37] +(x::BigFloat, y::BigFloat) in Base.MPFR at mpfr.jl:363
[38] +(x::BigFloat, c::Union{UInt16, UInt32, UInt64, UInt8}) in Base.MPFR at mpfr.jl:370
[39] +(x::BigFloat, c::Union{Int16, Int32, Int64, Int8}) in Base.MPFR at mpfr.jl:378
[40] +(x::BigFloat, c::Union{Float16, Float32, Float64}) in Base.MPFR at mpf

Determine the methods associated with this operator


In [176]:
@which 3 + 3 # Tells us that + is using T which is some kind of integer

+(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:86

In [177]:
@which 3.0 + 3.0

+(x::Float64, y::Float64) in Base at float.jl:401

In [178]:
@which 3+3.0

+(x::Number, y::Number) in Base at promotion.jl:311

To extend it, we need to import + from Base

In [179]:
import Base: +

We want to be able to concatenate strings with +

In [180]:
# "hello " + "world" # throws an error

In [181]:
+(x::String, y::String) = string(x, y)

+ (generic function with 208 methods)

In [182]:
"hello " + "world"

"hello world"

Now it works! Now we can check where the method is defined

In [183]:
@which "hello " + "world"

+(x::String, y::String) in Main at In[181]:1

In [184]:
foo(x, y) = println("Duck typed foo")
foo(x::Int, y::Float64) = println("foo with an integer and a float")
foo(x::Float64, y::Float64) = println("foo with 2 floats")
foo(x::Int, y::Int) = println("Foo with 2 ints")

foo (generic function with 4 methods)

In [185]:
foo(1, 1)
foo(1., 1.)
foo(1, 1.)
foo("a", "b")

Foo with 2 ints
foo with 2 floats
foo with an integer and a float
Duck typed foo


# Assignments

In [186]:
A = rand(1:4, 3, 3)

3×3 Array{Int64,2}:
 2  4  1
 2  1  2
 1  1  3

In [188]:
B = A
C = copy(A)
[ B C ] # Show side by side

3×6 Array{Int64,2}:
 2  4  1  2  4  1
 2  1  2  2  1  2
 1  1  3  1  1  3

In [189]:
A[1] = 17
[ B C ]

3×6 Array{Int64,2}:
 17  4  1  2  4  1
  2  1  2  2  1  2
  1  1  3  1  1  3

Now we see that because we didn't use `copy()` with `B = A`, it did a shallow (reference) assignment

# Basic Linear Algebra

In [190]:
x = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

### Multiplication

In [191]:
b = A*x

3-element Array{Float64,1}:
 22.0
  5.0
  5.0

### Transpose

`A'` is the conjugate transpose whereas `A.'` is the regular transpose

In [192]:
Asym = A + A'

3×3 Array{Int64,2}:
 34  6  2
  6  2  3
  2  3  6

### Transposed Multiplication

In [195]:
A'A # Multiplication is implied

3×3 Array{Int64,2}:
 294  71  24
  71  18   9
  24   9  14

The problem $Ax=b$ for square $A$ is solved by the `\` function

In [196]:
A\b

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

### Overdetermined systems

When $A$ is tall (not square) the `\` function calculates the least squares solution

In [197]:
Atall = A[:,1:2] # Keep all rows and only the first 2 columns of A
display(Atall)
Atall\b

3×2 Array{Int64,2}:
 17  4
  2  1
  1  1

2-element Array{Float64,1}:
 0.17529880478087645
 4.752988047808765

The `\` function also works for rank deficient least squares problems. In this case, the least square solution is not unique, so Julia returns the solution with the smallest norm.

In [198]:
A = randn(3, 3)

3×3 Array{Float64,2}:
 0.0952259  -2.22039   0.051345
 0.617777   -0.137439  0.412599
 2.17635     0.496936  0.381384

In [199]:
[A[:, 1] A[:, 1]]\b # Taking the outer product of a vector with itself

2-element Array{Float64,1}:
 1.5667013000584706
 1.5667013000584706

### Underdetermined systems

Where A is short the `\` function returns the minimum norm solution

In [200]:
Ashort = A[1:2, :]
display(Ashort)
Ashort\b[1:2]

2×3 Array{Float64,2}:
 0.0952259  -2.22039   0.051345
 0.617777   -0.137439  0.412599

3-element Array{Float64,1}:
  4.132030984255059
 -9.668255684934179
  2.7109385026957145